version: '2.3'
services: 
    db:
        container_name: bd_sql_iiq
        build: 
            context: ./sqlserver
        restart: always
        ports: 
            - 1433:1433
        command: 
            bash -c "sh -x /tmp/entrypoint.sh"
        healthcheck:
            test: [ "CMD","/opt/mssql-tools/bin/sqlcmd", "-S" , "localhost", "-U", "healthcheck", "-P", "Change@123", "-Q", "SELECT 1" ]
            timeout: 10s
            retries: 20
    
    iiq:
        build: ./tomcat
        restart: always
        ports: 
            - 8080:8080
            - 9009:9009
        container_name: web_iiq
        depends_on: 
            db:
                condition: service_healthy
        
                
